name: Example workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        if [ "${{ github.event.head_commit.message }}" ]; then
          echo "INSIDE THE IF STATEMENT"
        fi
        echo "Hello, world!"
